# Generated by Django 5.1.4 on 2026-04-22 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_nomiweb_compatibility'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payroll_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.payrolltype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='num_libreta_militar',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
