# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_nomiweb_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.CharField(blank=True, max_length=10, verbose_name='height (cm)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume_format',
            field=models.CharField(
                blank=True,
                choices=[('pdf', 'PDF'), ('word', 'Word'), ('physical', 'Físico')],
                max_length=25,
                verbose_name='resume format',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='weight',
            field=models.CharField(blank=True, max_length=10, verbose_name='weight (kg)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='legacy_contract_id',
            field=models.CharField(blank=True, max_length=25, verbose_name='legacy contract id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_pensioner',
            field=models.CharField(
                blank=True,
                choices=[
                    ('not_applicable', 'No aplica'),
                    ('active', 'Pensionado activo'),
                    ('substitution', 'Sustitución'),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('transfer', 'Transferencia'),
                    ('check', 'Cheque'),
                    ('cash', 'Efectivo'),
                ],
                max_length=25,
            ),
        ),
    ]
