# Generated by Django 5.1.4 on 2026-04-24 21:46

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_employee_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='nomiweb_contrato_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (contratos.idcontrato)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nomiweb_empleado_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (contratosemp.idempleado)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, upload_to='personnel/contracts/', validators=[apps.core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/resumes/', validators=[apps.core.validators.validate_document_file], verbose_name='resume file (PDF)'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='personnel/documents/', validators=[apps.core.validators.validate_document_file]),
        ),
    ]
