# Generated by Django 5.1.4 on 2026-04-25 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_tenant_nomiweb_parity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomiwebConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomiweb_empresa_id', models.IntegerField(help_text='ID de la empresa en Nomiweb (empresa.idempresa)')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Si False, los webhooks se ignoran para este tenant')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('success', 'Exitosa'), ('partial', 'Parcial'), ('error', 'Error'), ('never', 'Nunca sincronizado')], default='never', max_length=20)),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomiweb_config', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Configuración Nomiweb',
                'verbose_name_plural': 'Configuraciones Nomiweb',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('nomiweb_to_hcm', 'Nomiweb → HCM'), ('hcm_to_nomiweb', 'HCM → Nomiweb')], max_length=20)),
                ('model_name', models.CharField(choices=[('tenant', 'Empresa/Tenant'), ('employee', 'Empleado'), ('contract', 'Contrato'), ('position', 'Cargo'), ('cost_center', 'Centro de Costo'), ('work_location', 'Sede'), ('nomina', 'Nómina'), ('vacacion', 'Vacación'), ('liquidacion', 'Liquidación'), ('catalog', 'Catálogo global')], max_length=30)),
                ('nomiweb_id', models.CharField(blank=True, max_length=50)),
                ('hcm_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('error', 'Error'), ('skipped', 'Omitido')], max_length=20)),
                ('action', models.CharField(blank=True, choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('skipped', 'Sin cambios')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-created_at'],
            },
        ),
    ]
