# Generated by Django 5.1.4 on 2026-04-19 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'catalog_absence_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('ach_code', models.CharField(blank=True, max_length=10)),
                ('nit', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'catalog_bank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contract_type', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_contract_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dian_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_contract_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContributorSubtype',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('form_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_contributor_subtype',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContributorType',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120)),
                ('form_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_contributor_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('iso_code', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'catalog_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'db_table': 'catalog_diagnosis',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
                ('dian_code', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'catalog_profession',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'catalog_salary_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9)),
                ('nit', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('entity_type', models.CharField(choices=[('EPS', 'EPS'), ('AFP', 'Fondo de Pensiones'), ('ARL', 'ARL'), ('CCF', 'Caja de Compensación'), ('CESANTIAS', 'Fondo de Cesantías')], max_length=20)),
                ('sgp_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'catalog_social_security_entity',
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('accounting_group', models.CharField(blank=True, max_length=4)),
                ('suffix', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'catalog_cost_center',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=60)),
                ('year', models.SmallIntegerField()),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogs.country')),
            ],
            options={
                'db_table': 'catalog_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'catalog_organizational_level',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.organizationallevel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'catalog_position',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.country')),
            ],
            options={
                'db_table': 'catalog_state_province',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('state_province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.stateprovince')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'catalog_city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('suffix', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.costcenter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'catalog_sub_cost_center',
                'ordering': ['cost_center__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('arl_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('economic_activity', models.CharField(blank=True, max_length=7)),
                ('operator_code', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'catalog_work_center',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('compensation_fund', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'CCF'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.socialsecurityentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'catalog_work_location',
                'ordering': ['name'],
            },
        ),
    ]
