# Generated by Django 5.1.4 on 2026-04-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_global_catalog_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('cod_dian', models.SmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_payroll_type',
                'ordering': ['nombre'],
            },
        ),
    ]
