# Generated by Django 5.1.4 on 2026-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_nomiweb_compatibility'),
        ('core', '0006_nomiweb_bridge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='nomiweb_costo_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (costos.idcosto)', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='nomiweb_cargo_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (cargos.idcargo)', null=True),
        ),
        migrations.AddField(
            model_name='subcostcenter',
            name='nomiweb_subcosto_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (subcostos.idsubcosto)', null=True),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='nomiweb_ct_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (centrotrabajo.centrotrabajo)', null=True),
        ),
        migrations.AddField(
            model_name='worklocation',
            name='nomiweb_sede_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (sedes.idsede)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('tenant', 'nomiweb_costo_id')},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('tenant', 'nomiweb_cargo_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subcostcenter',
            unique_together={('tenant', 'nomiweb_subcosto_id')},
        ),
        migrations.AlterUniqueTogether(
            name='workcenter',
            unique_together={('tenant', 'nomiweb_ct_id')},
        ),
        migrations.AlterUniqueTogether(
            name='worklocation',
            unique_together={('tenant', 'nomiweb_sede_id')},
        ),
    ]
