# Generated by Django 5.1.4 on 2026-04-20 23:00

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogs', '0001_initial'),
        ('core', '0002_roles_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='arl',
            field=models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'ARL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants_as_arl', to='catalogs.socialsecurityentity'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='certification_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='certification title'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='catalogs.city'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='catalogs.country'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='database_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='database name'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='verification digit'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='document_type',
            field=models.CharField(blank=True, default='', help_text='e.g. N.I.T', max_length=50, verbose_name='company document type'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='company email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_representative',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='legal representative'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.models.tenant_logo_upload_to, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signature',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.models.tenant_signature_upload_to, verbose_name='certification signature'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='tenantmodules',
            name='evaluations',
            field=models.BooleanField(default=False, verbose_name='evaluations'),
        ),
    ]
