# Generated by Django 5.1.4 on 2026-04-24 21:46

import apps.core.models
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_managers_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='nomiweb_empresa_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del registro equivalente en Nomiweb (empresa.idempresa)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.models.tenant_logo_upload_to, validators=[apps.core.validators.validate_image_file], verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='signature',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.models.tenant_signature_upload_to, validators=[apps.core.validators.validate_image_file], verbose_name='certification signature'),
        ),
    ]
