# Generated by Django 5.1.4 on 2026-04-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_nomiweb_bridge_fields'),
        ('core', '0006_nomiweb_bridge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='banco_empresa',
            field=models.ForeignKey(blank=True, help_text='Banco donde la empresa tiene cuenta para pagos de nómina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_banco', to='catalogs.bank'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cargo_certificaciones',
            field=models.CharField(blank=True, help_text='Cargo del firmante de certificaciones laborales', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='clase_aportante',
            field=models.CharField(blank=True, help_text='Clase de aportante PILA (01=Empleador, etc.)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='codigo_sucursal',
            field=models.CharField(blank=True, help_text='Código de sucursal para planilla PILA tipo S', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contacto_contabilidad',
            field=models.CharField(blank=True, help_text='Nombre del contacto de contabilidad', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contacto_nomina',
            field=models.CharField(blank=True, help_text='Nombre del contacto de nómina', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contacto_rrhh',
            field=models.CharField(blank=True, help_text='Nombre del contacto de RRHH', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito de verificación del NIT', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_contabilidad',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_nomina',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_rrhh',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='empresa_exonerada',
            field=models.BooleanField(default=False, help_text='Si la empresa está exonerada de parafiscales (Ley 1607)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='firma_certificaciones',
            field=models.ImageField(blank=True, help_text='Firma digital para certificaciones laborales', null=True, upload_to='tenants/firmas_cert/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ige100',
            field=models.BooleanField(default=False, help_text='Incapacidad general de enfermedad al 100%'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='naturaleza_juridica',
            field=models.CharField(blank=True, choices=[('1', 'Sociedad Anónima'), ('2', 'Sociedad Limitada'), ('3', 'Empresa Unipersonal'), ('4', 'SAS'), ('5', 'Otra')], help_text='Naturaleza jurídica de la empresa', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nombre_sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='num_cuenta_empresa',
            field=models.CharField(blank=True, help_text='Número de cuenta bancaria de la empresa', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='numero_doc_rep_legal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='papellido_rep_legal',
            field=models.CharField(blank=True, help_text='Primer apellido del representante legal', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pnombre_rep_legal',
            field=models.CharField(blank=True, help_text='Primer nombre del representante legal', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='realizar_parafiscales',
            field=models.BooleanField(default=True, help_text='Si la empresa liquida parafiscales en nómina'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sapellido_rep_legal',
            field=models.CharField(blank=True, help_text='Segundo apellido del representante legal', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sln_tarifa_pension',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa de pensión (default 16.00%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='snombre_rep_legal',
            field=models.CharField(blank=True, help_text='Segundo nombre del representante legal', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_aportante',
            field=models.CharField(blank=True, help_text='Tipo de aportante PILA', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_cuenta_empresa',
            field=models.CharField(blank=True, choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_doc_rep_legal',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula extranjería'), ('PA', 'Pasaporte'), ('CD', 'Carnet diplomático')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('N', 'Natural'), ('J', 'Jurídica')], help_text='Tipo de persona (N=Natural, J=Jurídica)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_presentacion_planilla',
            field=models.CharField(blank=True, choices=[('U', 'Única'), ('S', 'Sucursal')], help_text='Tipo de presentación de planilla PILA', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vst_ccf',
            field=models.BooleanField(default=True, help_text='Aporta a Caja de Compensación Familiar'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vst_sena_icbf',
            field=models.BooleanField(default=True, help_text='Aporta a SENA e ICBF'),
        ),
    ]
