# Generated by Django 5.1.4 on 2026-04-19 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(max_length=255)),
                ('requested_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('positions_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personnel.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'hiring process',
                'verbose_name_plural': 'hiring processes',
                'db_table': 'hiring_process',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('resume', models.FileField(blank=True, upload_to='hiring/resumes/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_candidate', to='personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('hiring_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hiring.hiringprocess')),
            ],
            options={
                'verbose_name': 'candidate',
                'verbose_name_plural': 'candidates',
                'db_table': 'hiring_candidate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'onboarding checklist',
                'verbose_name_plural': 'onboarding checklists',
                'db_table': 'hiring_onboarding_checklist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiring.onboardingchecklist')),
            ],
            options={
                'verbose_name': 'employee onboarding',
                'verbose_name_plural': 'employee onboardings',
                'db_table': 'hiring_employee_onboarding',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('responsible_role', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('days_to_complete', models.PositiveIntegerField(default=7)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hiring.onboardingchecklist')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'onboarding task',
                'verbose_name_plural': 'onboarding tasks',
                'db_table': 'hiring_onboarding_task',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='hiring.employeeonboarding')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.onboardingtask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'task completion',
                'db_table': 'hiring_task_completion',
                'ordering': ['task__order'],
                'unique_together': {('onboarding', 'task')},
            },
        ),
    ]
