# Generated by Django 5.1.4 on 2026-04-19 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('planned_date', models.DateField()),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('conclusions', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_led', to='personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'internal audit',
                'verbose_name_plural': 'internal audits',
                'db_table': 'quality_audit',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_type', models.CharField(choices=[('nonconformity_major', 'No Conformidad Mayor'), ('nonconformity_minor', 'No Conformidad Menor'), ('observation', 'Observación'), ('opportunity', 'Oportunidad de Mejora')], max_length=30)),
                ('clause', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='quality.internalaudit')),
            ],
            options={
                'verbose_name': 'audit finding',
                'verbose_name_plural': 'audit findings',
                'db_table': 'quality_audit_finding',
                'ordering': ['finding_type'],
            },
        ),
        migrations.CreateModel(
            name='QualityProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under Review'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personnel.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_processes', to='personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'quality process',
                'verbose_name_plural': 'quality processes',
                'db_table': 'quality_process',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='quality.qualityprocess'),
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('audit', 'Auditoría Interna'), ('external_audit', 'Auditoría Externa'), ('customer_complaint', 'Queja de Cliente'), ('process', 'Detección en Proceso'), ('employee', 'Reporte de Empleado')], max_length=30)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('immediate_action', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('verification', 'Verification'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_verified', models.BooleanField(default=False)),
                ('audit_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='quality.auditfinding')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformities_responsible', to='personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'nonconformity',
                'verbose_name_plural': 'nonconformities',
                'db_table': 'quality_nonconformity',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('procedure', 'Procedimiento'), ('instruction', 'Instrucción de Trabajo'), ('format', 'Formato'), ('record', 'Registro'), ('policy', 'Política'), ('manual', 'Manual')], max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('file', models.FileField(upload_to='quality/documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quality.qualityprocess')),
            ],
            options={
                'verbose_name': 'quality document',
                'verbose_name_plural': 'quality documents',
                'db_table': 'quality_document',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code', 'version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='internalaudit',
            unique_together={('tenant', 'code')},
        ),
        migrations.CreateModel(
            name='ContinuousImprovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expected_benefit', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvements_proposed', to='personnel.employee')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvements_assigned', to='personnel.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='improvements', to='quality.qualityprocess')),
            ],
            options={
                'verbose_name': 'continuous improvement',
                'verbose_name_plural': 'continuous improvements',
                'db_table': 'quality_improvement',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
